exclude_paths:
    - docs/**/*
    - tests/**/*
    - gii/**/*
    
ratings:
    paths:
        - behaviors/**
        - components/**
        - models/**
        - traits/**
        
engines:
    phpmd:
        enabled: true
    phpcodesniffer:
        enabled: true